Revert "Revert "Started wiring up Recipe Detail with Fragments but it doesn't build.  I get "error: incompatible types: inference variable T has incompatible upper bounds Fragment,View"""
This reverts commit cec3f1ec